function out1 = constraintHess_AdfPartTime_Nh5_2(in1)
%CONSTRAINTHESS_ADFPARTTIME_NH5_2
%    OUT1 = CONSTRAINTHESS_ADFPARTTIME_NH5_2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    18-Oct-2021 06:42:23

out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
