function out1 = constraintHess_AdfPartTime_Nh5_10(in1)
%CONSTRAINTHESS_ADFPARTTIME_NH5_10
%    OUT1 = CONSTRAINTHESS_ADFPARTTIME_NH5_10(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    18-Oct-2021 06:42:24

out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
